# DATABASE CONFIG
#DATABASE_URI = ''
MYSQL_DATABASE_USER = 'emanuel'
MYSQL_DATABASE_PASSWORD = 'root'
MYSQL_DATABASE_DB = 'friendsdb'
MYSQL_DATABASE_HOST = 'localhost'

# URL PREFIX CONFIG
PREFIX = ''

#INSTANCE PATH CONFIG
INSTANCE_PATH = '/var/www/friends/instance'

