# DATABASE CONFIG
#DATABASE_URI = ''
MYSQL_DATABASE_USER = ''
MYSQL_DATABASE_PASSWORD = ''
MYSQL_DATABASE_DB = 'friendsdb'
MYSQL_DATABASE_HOST = 'localhost'
PAGINATION_LIMIT = 5
POST_FIRST_CALL_LIMIT_1 = 90
POST_FIRST_CALL_LIMIT_2 = 25
REACTIONS_LIMIT = 100
COMMENTS_LIMIT = 20
FRIENDS_PER_QUARTILE = 5
FRIENDS_TOTAL_NUMBER = 20

# URL PREFIX CONFIG
PREFIX = ''

#INSTANCE PATH CONFIG
INSTANCE_PATH = '/var/www/friends/instance'

