-- MySQL Script generated by MySQL Workbench
-- Sun Jul 17 19:44:37 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

set global innodb_file_format = BARRACUDA;
SET GLOBAL innodb_file_per_table=ON;
set global innodb_large_prefix = ON;
-- -----------------------------------------------------
-- Schema friendsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friendsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friendsdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `friendsdb` ;

-- -----------------------------------------------------
-- Table `friendsdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`user` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`user` (
  `idhash` VARCHAR(128) NOT NULL,
  `id` VARCHAR(128) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `granted_permissions` TINYINT(1) NULL,
  PRIMARY KEY (`idhash`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`page` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`page` (
  `id` VARCHAR(128) NOT NULL,
  `name` VARCHAR(256) NULL,
  `category` VARCHAR(128) NULL,
  `total_fans` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`profile` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`profile` (
  `user_idhash` VARCHAR(128) NOT NULL,
  `birthday` VARCHAR(64) NULL,
  `gender` CHAR(1) NULL,
  `hometown_id` VARCHAR(128) NULL,
  `hometown_name` VARCHAR(256) NULL,
  `location_id` VARCHAR(128) NULL,
  `location_name` VARCHAR(256) NULL,
  `political_view` VARCHAR(256) NULL,
  `religion` VARCHAR(256) NULL,
  `interested_women` TINYINT(1) NULL,
  `interested_men` TINYINT(1) NULL,
  `relationship_status` VARCHAR(128) NULL,
  `language_1` VARCHAR(64) NULL,
  `language_2` VARCHAR(64) NULL,
  `language_3` VARCHAR(64) NULL,
  `language_4` VARCHAR(64) NULL,
  `language_5` VARCHAR(64) NULL,
  PRIMARY KEY (`user_idhash`),
  CONSTRAINT `fk_profile_user`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`place` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`place` (
  `id` VARCHAR(128) NOT NULL,
  `type` VARCHAR(128) NULL,
  `name` VARCHAR(256) NULL,
  `school_type` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`relationship` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`relationship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_idhash` VARCHAR(128) NOT NULL,
  `user_idhash1` VARCHAR(128) NOT NULL,
  `relationship_type` VARCHAR(128) NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relationship_user2_idx` (`user_idhash1` ASC),
  CONSTRAINT `fk_relationship_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationship_user2`
    FOREIGN KEY (`user_idhash1`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`reaction` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`reaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_idhash` VARCHAR(256) NOT NULL,
  `post_id` VARCHAR(256) NOT NULL,
  `comment_id` VARCHAR(256) NULL,
  `type` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reaction_user1_idx` (`user_idhash` ASC),
  CONSTRAINT `fk_reaction_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`post` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`post` (
  `local_id` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(256) NOT NULL,
  `user_idhash` VARCHAR(128) NOT NULL,
  `created_time` VARCHAR(128) NULL,
  `type` VARCHAR(128) NULL,
  `story` VARCHAR(256) NULL,
  `privacy` VARCHAR(128) NULL,
  `text_length` INT NULL,
  `link` VARCHAR(512) NULL,
  `nreactions` INT NULL,
  `ncomments` INT NULL,
  `application` VARCHAR(64) NULL,
  PRIMARY KEY (`local_id`),
  INDEX `fk_post_user1_idx` (`user_idhash` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`comment` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`comment` (
  `local_id` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(256) NOT NULL,
  `post_id` VARCHAR(256) NOT NULL,
  `user_idhash` VARCHAR(128) NOT NULL,
  `created_time` VARCHAR(128) NULL,
  `has_picture` TINYINT(1) NULL,
  `has_link` TINYINT(1) NULL,
  `nreactions` INT NULL,
  `ncomments` INT NULL,
  `text_lenght` INT NULL,
  PRIMARY KEY (`local_id`),
  INDEX `fk_comment_user1_idx` (`user_idhash` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`tag` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` VARCHAR(256) NOT NULL,
  `comment_id` VARCHAR(256) NULL,
  `type` VARCHAR(128) NULL,
  `user_idhash` VARCHAR(128) NULL,
  `page_id` VARCHAR(128) NULL,
  INDEX `fk_tag_user1_idx` (`user_idhash` ASC),
  INDEX `fk_tag_page1_idx` (`page_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tag_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_page1`
    FOREIGN KEY (`page_id`)
    REFERENCES `friendsdb`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`user_likes_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`user_likes_page` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`user_likes_page` (
  `user_idhash` VARCHAR(128) NOT NULL,
  `page_id` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`user_idhash`, `page_id`),
  INDEX `fk_user_has_page_page1_idx` (`page_id` ASC),
  INDEX `fk_user_has_page_user1_idx` (`user_idhash` ASC),
  CONSTRAINT `fk_user_has_page_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_page_page1`
    FOREIGN KEY (`page_id`)
    REFERENCES `friendsdb`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`comment_has_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`comment_has_comment` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`comment_has_comment` (
  `local_id` INT NOT NULL AUTO_INCREMENT,
  `comment_id` VARCHAR(256) NOT NULL,
  `comment_id1` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`local_id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`user_has_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`user_has_place` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`user_has_place` (
  `user_idhash` VARCHAR(128) NOT NULL,
  `place_id` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`user_idhash`, `place_id`),
  INDEX `fk_user_has_place_place1_idx` (`place_id` ASC),
  INDEX `fk_user_has_place_user1_idx` (`user_idhash` ASC),
  CONSTRAINT `fk_user_has_place_place1`
    FOREIGN KEY (`place_id`)
    REFERENCES `friendsdb`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_place_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`user_with_in_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`user_with_in_place` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`user_with_in_place` (
  `user_idhash` VARCHAR(128) NOT NULL,
  `user_has_place_user_idhash` VARCHAR(128) NOT NULL,
  `user_has_place_place_id` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`user_idhash`, `user_has_place_user_idhash`, `user_has_place_place_id`),
  INDEX `fk_user_has_user_has_place_user1_idx` (`user_idhash` ASC),
  INDEX `fk_user_with_in_place_user_has_place1_idx` (`user_has_place_user_idhash` ASC, `user_has_place_place_id` ASC),
  CONSTRAINT `fk_user_has_user_has_place_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_with_in_place_user_has_place1`
    FOREIGN KEY (`user_has_place_user_idhash` , `user_has_place_place_id`)
    REFERENCES `friendsdb`.`user_has_place` (`user_idhash` , `place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`user_in_place_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`user_in_place_details` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`user_in_place_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_has_place_user_idhash` VARCHAR(128) NOT NULL,
  `user_has_place_place_id` VARCHAR(128) NOT NULL,
  `school_concentration` VARCHAR(256) NULL,
  `location_id` VARCHAR(128) NULL,
  `location_name` VARCHAR(256) NULL,
  `position_id` VARCHAR(128) NULL,
  `position_name` VARCHAR(256) NULL,
  `start_date` VARCHAR(64) NULL,
  `end_date` VARCHAR(64) NULL,
  PRIMARY KEY (`id`, `user_has_place_user_idhash`, `user_has_place_place_id`),
  INDEX `fk_user_in_place_details_user_has_place1_idx` (`user_has_place_user_idhash` ASC, `user_has_place_place_id` ASC),
  CONSTRAINT `fk_user_in_place_details_user_has_place1`
    FOREIGN KEY (`user_has_place_user_idhash` , `user_has_place_place_id`)
    REFERENCES `friendsdb`.`user_has_place` (`user_idhash` , `place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`connectedness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`connectedness` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`connectedness` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_idhash` VARCHAR(128) NOT NULL,
  `user_idhash1` VARCHAR(128) NOT NULL,
  `connectedness_level` INT NULL,
  `f2f_interaction` INT NULL,
  `online_interaction` INT NULL,
  INDEX `fk_user_has_user_user2_idx` (`user_idhash1` ASC),
  INDEX `fk_user_has_user_user1_idx` (`user_idhash` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`user_idhash1`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


-- -----------------------------------------------------
-- Table `friendsdb`.`common_aspect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friendsdb`.`common_aspect` ;

CREATE TABLE IF NOT EXISTS `friendsdb`.`common_aspect` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_idhash` VARCHAR(128) NOT NULL,
  `user_idhash1` VARCHAR(128) NOT NULL,
  `type` VARCHAR(64) NULL,
  `description` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_user_user4_idx` (`user_idhash1` ASC),xx
  INDEX `fk_user_has_user_user3_idx` (`user_idhash` ASC),
  CONSTRAINT `fk_user_has_user_user3`
    FOREIGN KEY (`user_idhash`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user4`
    FOREIGN KEY (`user_idhash1`)
    REFERENCES `friendsdb`.`user` (`idhash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
